const FilterActionTypes = {
    TOGGLE_MEDIUM_RISK: 'TOGGLE_MEDIUM_RISK',
    TOGGLE_HIGH_RISK: 'TOGGLE_HIGH_RISK',
    TOGGLE_CRITICAL_RISK: 'TOGGLE_CRITICAL_RISK'
};

export default FilterActionTypes;